apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
  labels:
    app: fastapi-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
        - name: fastapi-container
          image: fastapi-service:latest  
          ports:
            - containerPort: 8008
          envFrom:
            - configMapRef:
                name: fastapi-config
          volumeMounts:
            - mountPath: /app/service
              name: service-volume
      volumes:
        - name: service-volume
          persistentVolumeClaim:
            claimName: service-pvc 
