version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_service
    env_file:
      - .env
    ports:
      - "8008:8008"
    volumes:
      - .:/app              
      - ./service:/app/service  
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8008
