[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Julio Rafael <juliorafaelnft@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.3"
uvicorn = "^0.32.0"
langchain = "^0.3.4"
langchain-core = "^0.3.12"
langchain-community = "^0.3.3"
openai = "^1.53.0"
langchain-openai = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
